### ISSUE TITLE
Server Failed to Load due to cute hermit crabs

### ISSUE THREAD

**Issue by dbiery1** [sv3r/CuteHermitCrabs#2]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 7/13/22, 11:26 AM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.18.2-40.1.60-universal.jar%2374!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.18.2-40.1.60-universal.jar%2374!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:112) ~[server-1.18.2-20220404.173914-srg.jar%2369!/:?] {re:classloading}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32) ~[fmlloader-1.18.2-40.1.60.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at me.sv3r.cutehermitcrabs.core.CuteHermitCrabs.<init>(CuteHermitCrabs.java:36) ~[CuteHermitCrabs-1.18.2-2.0.0.jar%2343!/:1.18.2-2.0.0] {re:classloading,pl:runtimedistcleaner:A}
-- MOD cutehermitcrabs --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:79) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:483) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.1.60.jar%2371!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.1.60.jar%2370!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: CuteHermitCrabs-1.18.2-2.0.0.jar
	Failure message: Cute Hermit Crabs (cutehermitcrabs) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 1.18.2-2.0.0
	Mod Issue URL: https://github.com/Sv3r/CuteHermitCrabs/issues
	Exception message: java.lang.NoSuchMethodError: 'void me.sv3r.cutehermitcrabs.core.CuteHermitCrabs.doClientStuff(net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent)'
Stacktrace:
	at me.sv3r.cutehermitcrabs.core.CuteHermitCrabs.<init>(CuteHermitCrabs.java:36) ~[CuteHermitCrabs-1.18.2-2.0.0.jar%2343!/:1.18.2-2.0.0] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:483) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.1.60.jar%2371!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.1.60.jar%2370!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 18.0.1.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1088268824 bytes (1037 MiB) / 1736441856 bytes (1656 MiB) up to 8573157376 bytes (8176 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-10100 CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: AMD Radeon RX 6500 XT
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4080.00
	Graphics card #0 deviceId: 0x743f
	Graphics card #0 versionInfo: DriverVersion=30.0.21017.1000
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37552.44
	Virtual memory used (MB): 16412.11
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 0.00
	JVM Flags: 0 total; 
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		server-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |COMMON_SET|Manifest: NOSIGNATURE
		more_underground_structures_1.18.2_6.jar          |more underground structures   |more_underground_structures   |5.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		H.e.b+v+1.2.1.jar                                 |Hals Enhanced Biomes          |heb                           |1.0                 |COMMON_SET|Manifest: NOSIGNATURE
		Piglin+Expansion+1.2+1.18.jar                     |Piglin Expansion              |piglin_expansion              |1.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		paucal-forge-1.18.2-0.4.7.jar                     |PAUCAL                        |paucal                        |0.4.7               |COMMON_SET|Manifest: NOSIGNATURE
		AwesomeDungeonNether-Forge-1.18.2-1.0.2.jar       |Awesome Dungeon Nether        |awesomedungeonnether          |1.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		verdure-1.18.2-1.1.2.jar                          |Verdure                       |verdure                       |1.1.2               |COMMON_SET|Manifest: NOSIGNATURE
		NextSpring-Forge-1.18.2-1.0.0.jar                 |QuickPlant                    |nextspring                    |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		blazegear-1.18.2-1.2.2.jar                        |Blaze Gear                    |blazegear                     |1.18.2-1.2.2        |COMMON_SET|Manifest: NOSIGNATURE
		LibraryFerret-Forge-1.18.2-2.0.0.jar              |Library ferret                |libraryferret                 |2.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		Natural+Decoration+v.1.0.8.jar                    |Natural Decoration            |natural_decoration            |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		Incendium_v5.0.4.jar                              |Incendium                     |incendium                     |0.0NONE             |COMMON_SET|Manifest: NOSIGNATURE
		Curses'+Naturals+1.0.0+-+1.18.2.jar               |Curses' Naturals              |curses_naturals               |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		VariantCraftingTables-1.18.2-1.5.4.jar            |Variant Crafting Tables       |variant_crafting_tables       |1.18.2-1.5.4        |COMMON_SET|Manifest: NOSIGNATURE
		diamethysts-1.5.0-1.18.2.jar                      |Diamethysts                   |diamethysts                   |1.5.0-1.18.2        |COMMON_SET|Manifest: NOSIGNATURE
		goblins-0.3.jar                                   |goblins                       |goblins                       |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		Unusual_Drill_1.18.2_V2.1.jar                     |Unusual Drill Mod             |unusual_drill_mod             |2.0                 |COMMON_SET|Manifest: NOSIGNATURE
		ferritecore-4.2.1-forge.jar                       |Ferrite Core                  |ferritecore                   |0.0NONE             |COMMON_SET|Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		CuteHermitCrabs-1.18.2-2.0.0.jar                  |Cute Hermit Crabs             |cutehermitcrabs               |1.18.2-2.0.0        |ERROR     |Manifest: NOSIGNATURE
		Rex's-AdditionalStructures-1.18.2-(v.3.1.0).jar   |Additional Structures         |additionalstructures          |3.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		bygonenether-1.1.2-1.18.2.jar                     |Bygone Nether                 |bygonenether                  |1.1.2               |COMMON_SET|Manifest: NOSIGNATURE
		Tiny_Chests.jar                                   |Tiny Chests                   |tiny_chests                   |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		Plus+The+End+V.1.1.9.jar                          |Plus The End                  |plus_the_end                  |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		glowinc-1.18.2_1.2.3.jar                          |Glow Inc.                     |glowinc                       |1.18.2_1.2.3        |COMMON_SET|Manifest: NOSIGNATURE
		lively-1.4.3.jar                                  |Lively                        |lively                        |1.4.3               |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.18.2-40.1.60-universal.jar                |Forge                         |forge                         |40.1.60             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Quick+Harvest-1.18.2-1.6.1.jar                    |Quick Harvest                 |quickharvest                  |1.6.1               |COMMON_SET|Manifest: NOSIGNATURE
		roasted-1.18.2-1.3.1.jar                          |Roasted                       |roasted                       |1.18.2-1.3.1        |COMMON_SET|Manifest: NOSIGNATURE
		simplemaps-0.3.1.jar                              |Simple Maps                   |simplemaps                    |0.3.1               |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 52b79829-86fe-4f5e-bef1-35b7d645db10
	FML: 40.1
	Forge: net.minecraftforge:40.1.60

**Comment by sv3r** [comment]
Hey

Thanks for notifying me about this. This should now be fixed in [this ](https://www.curseforge.com/minecraft/mc-mods/cute-hermit-crabs/files/3875289)version. If you encounter any other problems, please let me know. 

Regards
Sv3r
